/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package guis;

import control.ControlPlanGrafico;
import entidades.Macrociclo;
import enumeradores.Operacion;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yorsh
 */
public class PlanGraficoFrame extends javax.swing.JFrame {

    private Macrociclo macrociclo;
    private final ControlPlanGrafico controlPlanGrafico;
    private final Operacion operacion;

    public PlanGraficoFrame(Macrociclo macrociclo, Operacion operacion) {
        initComponents();
        
        this.macrociclo = macrociclo;
        this.operacion = operacion;
        this.controlPlanGrafico = new ControlPlanGrafico();
        this.controlPlanGrafico.setTableModel(this.planGrafico, this.macrociclo);
        
        switch (operacion) {
            case CREAR:
                this.controlPlanGrafico.cargarTabla((DefaultTableModel) this.planGrafico.getModel(), this.macrociclo.getMesociclos());
                this.btnAnterior.setVisible(false);
                break;
            case ACTUALIZAR:
                this.controlPlanGrafico.cargarTablaParaActualizar((DefaultTableModel) this.planGrafico.getModel(), macrociclo);
                this.btnGuardarMicrociclos.setText("Actualizar");
                this.btnAnterior.setVisible(true);
                break;
            case MOSTRAR:
                this.controlPlanGrafico.cargarTablaParaActualizar((DefaultTableModel) this.planGrafico.getModel(), macrociclo);
                this.btnGuardarMicrociclos.setVisible(false);
                this.btnAnterior.setVisible(true);
                this.planGrafico.setEnabled(false);
                break;
        }
        
        this.planGrafico.getTableHeader().setReorderingAllowed(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPanePlanGrafico = new javax.swing.JScrollPane();
        planGrafico = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnGuardarMicrociclos = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plan gráfico");

        planGrafico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollPanePlanGrafico.setViewportView(planGrafico);

        jLabel1.setText("Distribución de volumen plan gráfico");

        btnGuardarMicrociclos.setText("Guardar macrociclo");
        btnGuardarMicrociclos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMicrociclosActionPerformed(evt);
            }
        });

        btnAnterior.setText("Anterior página");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(385, 385, 385))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanePlanGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 908, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addGap(285, 285, 285)
                        .addComponent(btnGuardarMicrociclos)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanePlanGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMicrociclos)
                    .addComponent(btnAnterior))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarMicrociclosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMicrociclosActionPerformed
        if (this.operacion.equals(Operacion.ACTUALIZAR)) {
            this.controlPlanGrafico.actualizarMicrociclos(this, macrociclo, (DefaultTableModel) this.planGrafico.getModel());
        } else {
            this.controlPlanGrafico.guardarMacrociclo(this, macrociclo, (DefaultTableModel) this.planGrafico.getModel());
        }
    }//GEN-LAST:event_btnGuardarMicrociclosActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        new DistribucionVolumenFrame(macrociclo, operacion).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAnteriorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnGuardarMicrociclos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable planGrafico;
    private javax.swing.JScrollPane scrollPanePlanGrafico;
    // End of variables declaration//GEN-END:variables
}
